### ISSUE TITLE
Not clear 2 websites, gitlab, github

### ISSUE THREAD

**Issue by Neustradamus** [otrv4/pidgin-otr4#1]
Hello,

There are some problems for OTR:
- https://otr.cypherpunks.ca/
- http://otr.im/
- https://bugs.otr.im/explore

It is possible to redirect the old website (and all pages) to http://otr.im/ and add missing parts if there are?

See for the gitlab "bugs.otr.im".

It will be nice to update the old github and inform to move it.
https://github.com/off-the-record/

Archive too? and redirect?
- https://bugs.otr.im/plugins/pidgin-otr

**Comment by olabini** [comment]
Hi. This is not the relevant place to have this discussion. This repository is for an OTRv4 implementation of the Pidgin plugin. And since you have spammed a bunch of other places with exactly the same comment, I'm not sure you are very interested in having concrete and useful answers.
